version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # image: ghcr.io/andrewwade/arma3booter:latest  # Uncomment after first publish
    ports:
      - "45096:45096"
    environment:
      - NODE_ENV=production
      - DB_URL=${DB_URL}
    restart: unless-stopped 